steps:
  - name: golang:1.21
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
options:
  machineType: 'E2_HIGHCPU_32'
