steps:
  - name: golang:1.21
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        go install github.com/mgechev/revive@latest
        staticcheck ./...
options:
  machineType: 'E2_HIGHCPU_32'
