steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - USERNAME=user
    - SSH_ARGS=--internal-ip --ssh-key-expire-after=1d
    - INSTANCE_NAME=fp-build-arista-$BUILD_ID
    - INSTANCE_ARGS=--network cloudbuild-workers --image-project gep-kne --image-family kne --machine-type n2-standard-16 --preemptible
    - ZONE=us-west1-a
    - REMOTE_WORKSPACE=/tmp/workspace
    - COMMAND=sudo -iu user /tmp/workspace/cloudbuild/arista.sh
options:
  pool:
    name: 'projects/disco-idea-817/locations/us-west1/workerPools/featureprofiles-workerpool'
timeout: 1800s
