name: Go

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.21.x
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ github.job }}-${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
    - name: Build
      run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.21.x
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ github.job }}-${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      # Dependency for Go module github.com/google/gopacket
      - name: Install libpcap-dev
        run: sudo apt-get -y install libpcap-dev
      - run: go test -v -coverprofile=profile.cov $(go list ./... | grep -v /.*test.*)
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    # Go & staticcheck build cache require a lot of disk space.  Reclaim extra
    # space for the container by removing unnecessary tooling.
    - name: Free additional disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        WORKSPACE_OWNER="$(stat -c '%U:%G' "${GITHUB_WORKSPACE}")"
        sudo mkdir /mnt/cache && sudo chown "${WORKSPACE_OWNER}" /mnt/cache
        echo HOME=${HOME}
        ls -laR ${HOME}/.cache || true
        rm -rf ${HOME}/.cache
        ln -s /mnt/cache "${HOME}/.cache"
        ls -la ${HOME} || true
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/.cache/staticcheck
        key: ${{ github.job }}-${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
    # Dependency for Go module github.com/google/gopacket
    - name: Install libpcap-dev
      run: sudo apt-get -y install libpcap-dev
    - name: Go vet
      run: GOGC=30 go vet ./...
    - name: Gofmt
      run: |
        # gofmt always returns true, so we use grep '^' which returns
        # true on non-empty output, but will otherwise passthrough all
        # output lines.
        if gofmt -d -s . | grep '^'; then
          exit 1
        fi
    - name: Get goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    - name: Goimports
      run: |
        # goimports always returns true, so we use grep '^' which returns
        # true on non-empty output, but will otherwise passthrough all
        # output lines.
        #
        # goimports does not support "gofmt -s" so both goimports and gofmt are
        # required.
        find . -name "*.go" | egrep -v "pb.go$" | while read l; do
          if goimports -d $l | grep '^'; then
            exit 1;
          fi;
        done
    - name: Get revive
      run: go install github.com/mgechev/revive@v1.3.4
    - name: Run revive
      run: revive ./...
    - name: Get staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: print disk usage
      run: |
        ls -la /
        echo du -sh /tmp
        du -sh /tmp || true
        echo ls -la /tmp
        ls -la /tmp || true
        echo du -sh .
        du -sh . || true
        echo df -h
        df -h || true
        echo du -sh ../
        du -sh ../ || true
        echo du -sh /home/runner/.cache/*
        du -sh /home/runner/.cache/* || true
        echo ls -la /home
        ls -la /home
        echo ls -la /home/runner
        ls -la /home/runner
    - name: Run staticcheck
      run: GOGC=30 staticcheck ./...
    - name: print disk usage
      run: |
        ls -la /
        echo du -sh /tmp
        du -sh /tmp || true
        echo ls -la /tmp
        ls -la /tmp || true
        echo du -sh .
        du -sh . || true
        echo df -h
        df -h || true
        echo du -sh ../
        du -sh ../ || true
        echo du -sh /home/runner/.cache/*
        du -sh /home/runner/.cache/* || true
        echo ls -la /home
        ls -la /home  || true
        echo ls -la /home/runner
        ls -la /home/runner  || true
        echo pwd
        pwd  || true
        echo ls -la /home/runner/work
        ls -la /home/runner/work  || true
        echo ls -la /home/runner/work/featureprofiles/
        ls -la /home/runner/work/featureprofiles/ || true
        echo du -sh /home/runner/work/
        du -sh /home/runner/work/ || true
        echo ls -laR /mnt
        ls -laR /mnt || true
